api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: proxy
    exposedByDefault: false
  file:
    directory: /etc/traefik/config/
    watch: true

certificatesResolvers:
  web:
    acme:
      email: <email-address>
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web
